# Generated by Django 3.0.2 on 2020-02-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nom',
            field=models.CharField(max_length=30),
        ),
    ]
