# Generated by Django 3.0.2 on 2020-01-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallerie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoModel',
            new_name='MyPhotoModel',
        ),
    ]
